name: CDK Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r cdk_app/requirements.txt
          pip install -r tests/requirements.txt
          
      - name: Install CDK CLI
        run: |
          npm install -g aws-cdk

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests

      - name: CDK Synth
        run: |
          cdk synth -a "python cdk_app/app.py"

      - name: Deploy to AWS
        run: |
          cdk deploy \
          --app "python cdk_app/app.py" \
          --require-approval never 
          
